services:
  - type: web
    name: adigen-downloader-api
    env: node
    buildCommand: "npm install && python3 -m pip install --user yt-dlp"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://adigen.media
      - key: PORT
        value: 5000
